package kontor:contract;

world contract {
    include kontor:built-in/built-in;
    use kontor:built-in/context.{view-context, proc-context, signer};
    use kontor:built-in/error.{error};

    export init: func(ctx: borrow<proc-context>);

    export mint: func(ctx: borrow<proc-context>, n: u64);
    export transfer: func(ctx: borrow<proc-context>, to: string, n: u64) -> result<_, error>;
    export balance: func(ctx: borrow<view-context>, acc: string) -> option<u64>;
}
