package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/foreign.{contract-address};
  use kontor:built-in/context.{view-context, proc-context};
  use kontor:built-in/error.{error};

  record operand {
    y: u64,
  }

  variant op {
    id,
    sum(operand),
    mul(operand),
    div(operand),
  }

  record arith-return {
    value: u64
  }

  export init: async func(ctx: borrow<proc-context>);

  export eval: async func(ctx: borrow<proc-context>, x: u64, op: op) -> arith-return;

  export last-op: async func(ctx: borrow<view-context>) -> option<op>;

  export checked-sub: async func(ctx: borrow<view-context>, x: string, y: string) -> result<u64, error>;

  export fib: async func(ctx: borrow<proc-context>, contract-address: contract-address, n: u64) -> u64;
}
