package kontor:contract;

world contract {
    include kontor:built-in/built-in;
    use kontor:built-in/foreign.{contract-address};
    use kontor:built-in/context.{view-context, proc-context};
    use kontor:built-in/error.{error};

    record operand {
        y: u64,
    }

    variant op {
        id,
        sum(operand),
        mul(operand),
        div(operand),
    }

    record arith-return {
        value: u64
    }

    export init: func(ctx: borrow<proc-context>);

    export eval: func(ctx: borrow<proc-context>, x: u64, op: op) -> arith-return;

    export last-op: func(ctx: borrow<view-context>) -> option<op>;

    export checked-sub: func(ctx: borrow<view-context>, x: string, y: string) -> result<u64, error>;

    export fib: func(ctx: borrow<proc-context>, contract-address: contract-address, n: u64) -> u64;
}
