// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[derive(Debug)]
#[repr(transparent)]
pub struct Monoid {
    handle: _rt::Resource<Monoid>,
}
impl Monoid {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
        Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
        }
    }
    #[doc(hidden)]
    pub fn take_handle(&self) -> u32 {
        _rt::Resource::take_handle(&self.handle)
    }
    #[doc(hidden)]
    pub fn handle(&self) -> u32 {
        _rt::Resource::handle(&self.handle)
    }
}
unsafe impl _rt::WasmResource for Monoid {
    #[inline]
    unsafe fn drop(_handle: u32) {
        #[cfg(not(target_arch = "wasm32"))]
        unreachable!();
        #[cfg(target_arch = "wasm32")]
        {
            #[link(wasm_import_module = "$root")]
            unsafe extern "C" {
                #[link_name = "[resource-drop]monoid"]
                fn drop(_: u32);
            }
            unsafe { drop(_handle) };
        }
    }
}
impl Monoid {
    #[allow(unused_unsafe, clippy::all)]
    pub fn new(address: u64) -> Self {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "$root")]
            unsafe extern "C" {
                #[link_name = "[constructor]monoid"]
                fn wit_import0(_: i64) -> i32;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i64) -> i32 {
                unreachable!()
            }
            let ret = unsafe { wit_import0(_rt::as_i64(&address)) };
            unsafe { Monoid::from_handle(ret as u32) }
        }
    }
}
impl Monoid {
    #[allow(unused_unsafe, clippy::all)]
    pub fn mzero(&self) -> u64 {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "$root")]
            unsafe extern "C" {
                #[link_name = "[method]monoid.mzero"]
                fn wit_import0(_: i32) -> i64;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32) -> i64 {
                unreachable!()
            }
            let ret = unsafe { wit_import0((self).handle() as i32) };
            ret as u64
        }
    }
}
impl Monoid {
    #[allow(unused_unsafe, clippy::all)]
    pub fn mappend(&self, x: u64, y: u64) -> u64 {
        unsafe {
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "$root")]
            unsafe extern "C" {
                #[link_name = "[method]monoid.mappend"]
                fn wit_import0(_: i32, _: i64, _: i64) -> i64;
            }
            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, _: i64, _: i64) -> i64 {
                unreachable!()
            }
            let ret = unsafe {
                wit_import0((self).handle() as i32, _rt::as_i64(&x), _rt::as_i64(&y))
            };
            ret as u64
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_fib_cabi<T: Guest>(arg0: i64) -> i64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::fib(arg0 as u64);
    _rt::as_i64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_api_twice_cabi<T: Guest>(arg0: i64, arg1: i64) -> i64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::api_twice(arg0 as u64, arg1 as u64);
    _rt::as_i64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_twice_cabi<T: Guest>(arg0: i32, arg1: i64) -> i64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::twice(unsafe { Monoid::from_handle(arg0 as u32) }, arg1 as u64);
    _rt::as_i64(result0)
}
pub trait Guest {
    fn fib(n: u64) -> u64;
    fn api_twice(address: u64, n: u64) -> u64;
    fn twice(m: Monoid, n: u64) -> u64;
}
#[doc(hidden)]
macro_rules! __export_world_fib_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "fib")] unsafe extern "C" fn
        export_fib(arg0 : i64,) -> i64 { unsafe { $($path_to_types)*::
        _export_fib_cabi::<$ty > (arg0) } } #[unsafe (export_name = "api-twice")] unsafe
        extern "C" fn export_api_twice(arg0 : i64, arg1 : i64,) -> i64 { unsafe {
        $($path_to_types)*:: _export_api_twice_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "twice")] unsafe extern "C" fn export_twice(arg0 : i32, arg1 :
        i64,) -> i64 { unsafe { $($path_to_types)*:: _export_twice_cabi::<$ty > (arg0,
        arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_fib_cabi;
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_fib_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_fib_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_fib_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:fib:fib:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 353] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe7\x01\x01A\x02\x01\
A\x0f\x03\0\x06monoid\x03\x01\x01i\0\x01@\x01\x07addressw\0\x01\x03\0\x13[constr\
uctor]monoid\x01\x02\x01h\0\x01@\x01\x04self\x03\0w\x03\0\x14[method]monoid.mzer\
o\x01\x04\x01@\x03\x04self\x03\x01xw\x01yw\0w\x03\0\x16[method]monoid.mappend\x01\
\x05\x01@\x01\x01nw\0w\x04\0\x03fib\x01\x06\x01@\x02\x07addressw\x01nw\0w\x04\0\x09\
api-twice\x01\x07\x01@\x02\x01m\x01\x01nw\0w\x04\0\x05twice\x01\x08\x04\0\x11com\
ponent:fib/fib\x04\0\x0b\x09\x01\0\x03fib\x03\0\0\0G\x09producers\x01\x0cprocess\
ed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
