// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Block = {
  height: number;
  hash: string;
  prev_hash: string;
  transactions: Array<Transaction>;
};

export type BlockRow = { height: number; hash: string; relevant: boolean };

export type CommitOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_inputs: RevealInputs;
};

export type ComposeOutputs = {
  commit_transaction: string;
  commit_transaction_hex: string;
  commit_psbt_hex: string;
  reveal_transaction: string;
  reveal_transaction_hex: string;
  reveal_psbt_hex: string;
  per_participant: Array<ParticipantScripts>;
};

export type ComposeQuery = {
  instructions: Array<InstructionQuery>;
  sat_per_vbyte: number;
  envelope: number | null;
};

export type ContractListRow = {
  id: number;
  name: string;
  height: number;
  tx_index: number;
  size: number;
};

export type ContractResponse = { wit: string };

export type ErrorResponse = { error: string };

export type Event = { "type": "Processed"; block: Block } | {
  "type": "Rolledback";
  height: number;
};

export type Info = {
  version: string;
  target: string;
  available: boolean;
  height: number;
  checkpoint: string | null;
};

export type Inst =
  | { "Publish": { gas_limit: number; name: string; bytes: Array<number> } }
  | { "Call": { gas_limit: number; contract: string; expr: string } }
  | "Issuance";

export type InstructionQuery = {
  address: string;
  x_only_public_key: string;
  funding_utxo_ids: string;
  instruction: Inst;
  chained_instruction: Inst | null;
};

export type Op = {
  "Publish": {
    metadata: OpMetadata;
    gas_limit: number;
    name: string;
    bytes: Array<number>;
  };
} | {
  "Call": {
    metadata: OpMetadata;
    gas_limit: number;
    contract: string;
    expr: string;
  };
} | { "Issuance": { metadata: OpMetadata } };

export type OpMetadata = {
  previous_output: string;
  input_index: number;
  signer: Signer;
};

export type OpWithResult = { op: Op; result: ResultRow | null };

export type PaginatedResponse<T> = {
  results: Array<T>;
  pagination: PaginationMeta;
};

export type PaginationMeta = {
  next_cursor?: string;
  next_offset: number | null;
  has_more: boolean;
  total_count: number;
};

export type ParticipantScripts = {
  address: string;
  x_only_public_key: string;
  commit_tap_leaf_script: TapLeafScript;
  chained_tap_leaf_script: TapLeafScript | null;
};

export type ResultResponse<T> = { result: T };

export type ResultRow = {
  id: number;
  height: number;
  tx_index: number;
  input_index: number;
  op_index: number;
  result_index: number;
  func: string;
  gas: number;
  value: string | null;
  contract: string;
};

export type RevealInputs = {
  commit_tx: string;
  fee_rate: number;
  participants: Array<RevealParticipantInputs>;
  op_return_data: Array<number> | null;
  envelope: number;
};

export type RevealOutputs = {
  transaction: string;
  transaction_hex: string;
  psbt_hex: string;
  participants: Array<ParticipantScripts>;
};

export type RevealParticipantInputs = {
  address: string;
  x_only_public_key: string;
  commit_outpoint: string;
  commit_prevout: TxOutSchema;
  commit_tap_leaf_script: TapLeafScript;
  chained_instruction: Array<number> | null;
};

export type RevealParticipantQuery = {
  address: string;
  x_only_public_key: string;
  commit_vout: number;
  commit_script_data: Array<number>;
  chained_instruction: Array<number> | null;
};

export type RevealQuery = {
  commit_tx_hex: string;
  sat_per_vbyte: number;
  participants: Array<RevealParticipantQuery>;
  op_return_data: Array<number> | null;
  envelope: number | null;
};

export type Signer = { "Core": Signer } | { "XOnlyPubKey": string } | {
  "ContractId": { id: number; id_str: string };
} | "Nobody";

export type TapLeafScript = {
  leafVersion: number;
  script: string;
  controlBlock: string;
};

export type Transaction = {
  txid: string;
  index: number;
  ops: Array<Op>;
  op_return_data: Record<number, OpReturnData>;
};

export type TransactionHex = { hex: string };

export type TransactionRow = {
  id: number;
  txid: string;
  height: number;
  tx_index: number;
};

export type TxOutSchema = { value: number; script_pubkey: string };

export type ViewExpr = { expr: string };

export type ViewResult = { "type": "Ok"; value: string } | {
  "type": "Err";
  message: string;
};

export type WsRequest = { "type": "Subscribe" };

export type WsResponse = { "type": "Event"; event: Event } | {
  "type": "Error";
  error: string;
};
