package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/context.{view-context, proc-context, signer};
  use kontor:built-in/error.{error};
  use kontor:built-in/foreign.{contract-address};
  use kontor:built-in/numbers.{integer, decimal};

  export init: async func(ctx: borrow<proc-context>);

  export open: async func(ctx: borrow<proc-context>, token: contract-address, n: integer, other-tenants: list<string>) -> result<string, error>;

  export deposit: async func(ctx: borrow<proc-context>, token: contract-address, account-id: string, n: integer) -> result<_, error>;

  export withdraw: async func(ctx: borrow<proc-context>, token: contract-address, account-id: string, n: integer) -> result<_, error>;

  export balance: async func(ctx: borrow<view-context>, account-id: string) -> option<integer>;

  export token-balance: async func(ctx: borrow<view-context>, token: contract-address, holder: string) -> option<integer>;

  export tenants: async func(ctx: borrow<view-context>, account-id: string) -> option<list<string>>;
}
