extern crate proc_macro;

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{DeriveInput, Fields, ItemStruct, parse_macro_input};

#[proc_macro_derive(HelloWorld)]
pub fn hello_world_derive(input: TokenStream) -> TokenStream {
    let ast = parse_macro_input!(input as DeriveInput);
    let name = &ast.ident;

    quote! {
        impl #name {
            pub fn hello_world() {
                println!("Hello, World! from {} generated by HelloWorld macro!", stringify!(#name));
            }
        }
    }
    .into()
}

#[proc_macro_attribute]
pub fn storage(_attr: TokenStream, item: TokenStream) -> TokenStream {
    // Parse the input tokens into a struct
    let input = parse_macro_input!(item as ItemStruct);
    let name = &input.ident;

    // Ensure the input is a struct with named fields
    let fields = match input.fields {
        Fields::Named(ref fields) => &fields.named,
        _ => panic!("storage attribute macro only supports structs with named fields"),
    };

    // Generate getter and setter methods for each u64 field
    let mut methods = Vec::new();
    for field in fields {
        let field_name = field.ident.as_ref().unwrap();
        let field_type = &field.ty;

        // Only process u64 fields for now
        if let syn::Type::Path(type_path) = field_type {
            if type_path.path.is_ident("u64") {
                let getter = quote! {
                    pub fn #field_name(&self) -> u64 {
                        get(stringify!(#field_name)).unwrap().parse().unwrap()
                    }
                };

                let setter_name = format_ident!("set_{}", field_name);
                let setter = quote! {
                    pub fn #setter_name(&mut self, value: u64) {
                        set(stringify!(#field_name), &value.to_string());
                    }
                };

                methods.push(getter);
                methods.push(setter);
            }
        }
    }

    // Generate the new method with default values (0 for u64)
    let new_fields = fields.iter().map(|field| {
        let field_name = field.ident.as_ref().unwrap();
        quote! {
            #field_name: 0
        }
    });

    let expanded = quote! {
        #[allow(unused)]
        #input

        impl #name {
            pub fn new() -> Self {
                Self {
                    #(#new_fields),*
                }
            }

            #(#methods)*
        }
    };

    TokenStream::from(expanded)
}
