package kontor:contract;

world contract {
    include kontor:built-in/built-in;
    use kontor:built-in/context.{core-context, view-context, proc-context, signer};
    use kontor:built-in/error.{error};
    use kontor:built-in/numbers.{decimal};

    record balance {
  		key: string,
  		value: decimal,
  	}

    export init: func(ctx: borrow<proc-context>);

    export issuance: func(ctx: borrow<core-context>, to: string);

    export mint: func(ctx: borrow<proc-context>, n: decimal);
    export transfer: func(ctx: borrow<proc-context>, to: string, n: decimal) -> result<_, error>;
    export balance: func(ctx: borrow<view-context>, acc: string) -> option<decimal>;
    export balances: func(ctx: borrow<view-context>) -> list<balance>;
    export total-supply: func(ctx: borrow<view-context>) -> decimal;
}
