package root:component;

world root {
	include kontor:built-in/built-in;
	use kontor:built-in/context.{core-context, view-context, proc-context, signer};
	use kontor:built-in/error.{error};
	use kontor:built-in/numbers.{decimal};

  record balance {
		key: string,
		value: decimal,
	}

	export issuance: func(ctx: borrow<core-context>, n: decimal);
	export hold: func(ctx: borrow<core-context>, n: decimal) -> result<_, error>;
	export burn-and-release: func(ctx: borrow<core-context>, n: decimal) -> result<_, error>;

	export init: func(ctx: borrow<proc-context>);

	export mint: func(ctx: borrow<proc-context>, n: decimal);
	export burn: func(ctx: borrow<proc-context>, n: decimal) -> result<_, error>;
	export transfer: func(ctx: borrow<proc-context>, to: string, n: decimal) -> result<_, error>;
	export balance: func(ctx: borrow<view-context>, acc: string) -> option<decimal>;
	export balances: func(ctx: borrow<view-context>) -> list<balance>;
	export total-supply: func(ctx: borrow<view-context>) -> decimal;
}
