package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/context.{core-context, view-context, proc-context, signer};
  use kontor:built-in/error.{error};
  use kontor:built-in/numbers.{decimal};

  record balance {
    acc: string,
    amt: decimal,
  }

  record transfer {
    src: string,
    dst: string,
    amt: decimal,
  }

  record burn {
    src: string,
    amt: decimal,
  }

  record mint {
    dst: string,
    amt: decimal,
  }

  export issuance: func(ctx: borrow<core-context>, amt: decimal) -> result<mint, error>;
  export hold: func(ctx: borrow<core-context>, amt: decimal) -> result<transfer, error>;
  export release: func(ctx: borrow<core-context>, burn-amt: decimal) -> result<burn, error>;

  export init: func(ctx: borrow<proc-context>);

  export mint: func(ctx: borrow<proc-context>, amt: decimal) -> result<mint, error>;
  export burn: func(ctx: borrow<proc-context>, amt: decimal) -> result<burn, error>;
  export transfer: func(ctx: borrow<proc-context>, dst: string, amt: decimal) -> result<transfer, error>;
  export balance: func(ctx: borrow<view-context>, acc: string) -> option<decimal>;
  export balances: func(ctx: borrow<view-context>) -> list<balance>;
  export total-supply: func(ctx: borrow<view-context>) -> decimal;
  export attach: func(ctx: borrow<proc-context>, vout: u64, amt: decimal) -> result<transfer, error>;
  export detach: func(ctx: borrow<proc-context>) -> result<transfer, error>;
}
