package kontor:contract;

world contract {
    include kontor:built-in/built-in;
    use kontor:built-in/context.{proc-context};

    record sum-args {
        x: u64,
        y: u64,
    }

    record sum-return {
        value: u64,
    }

    export init: func(ctx: borrow<proc-context>);

    export sum: func(ctx: borrow<proc-context>, args: sum-args) -> sum-return;
}
