name: Setup Docker
description: Install and start Docker if not already running

runs:
  using: composite
  steps:
    - name: Install and start Docker
      shell: bash
      run: |
        # Check if Docker is already running
        if docker info >/dev/null 2>&1; then
          echo "Docker is already running"
          exit 0
        fi

        # Check if Docker is installed
        if ! command -v docker &> /dev/null; then
          echo "Docker not found. Installing Docker..."
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          echo "Docker installed successfully"
        fi

        # Try to start Docker
        if systemctl list-units --type=service --all | grep -q docker.service; then
          echo "Starting Docker via systemctl..."
          sudo systemctl start docker
        elif systemctl list-units --type=service --all | grep -q snap.docker.dockerd.service; then
          echo "Starting Docker via snap..."
          sudo systemctl start snap.docker.dockerd
        elif [ -f /etc/init.d/docker ]; then
          echo "Starting Docker via init.d..."
          sudo service docker start
        fi

        # Add current user to docker group if not already
        if ! groups | grep -q docker; then
          echo "Adding user to docker group..."
          sudo usermod -aG docker $USER
        fi

        # Make docker socket accessible (group membership won't take effect until new login)
        echo "Making Docker socket accessible..."
        sudo chmod 666 /var/run/docker.sock

        # Wait for Docker to be ready
        for i in {1..30}; do
          if docker info >/dev/null 2>&1; then
            echo "Docker is ready and accessible"
            exit 0
          fi
          echo "Waiting for Docker to start... ($i/30)"
          sleep 1
        done

        echo "ERROR: Docker failed to start"
        exit 1
