package kontor:contract;

interface stdlib {
    resource monoid {
        constructor(address: u64);
        mzero: func() -> u64;
        mappend: func(x: u64, y: u64) -> u64;
    }

    resource foreign {
        constructor(address: string);
        call: func(expr: string) -> string;
    }
}

world contract {
    use stdlib.{monoid, foreign};
    import sum: func(x: u64, y: u64) -> u64;
    export fib: func(n: u64) -> u64;

    export api-twice: func(address: u64, n: u64) -> u64;
    export twice: func(m: monoid, n: u64) -> u64;
}