package kontor:contract;

interface stdlib {
    set: func(key: string, value: string);
    get: func(key: string) -> option<string>;

    resource monoid {
        constructor(address: u64);
        mzero: func() -> u64;
        mappend: func(x: u64, y: u64) -> u64;
    }
}

world contract {
    import stdlib;
}
